export type UserRole = "FARMER" | "BUYER" | "AGENT" | "SERVICE_PROVIDER" | "ADMIN";

export type UserStatus = "ACTIVE" | "PENDING_VERIFICATION" | "SUSPENDED";

export const PUBLIC_ROLES: UserRole[] = ["FARMER", "BUYER", "AGENT", "SERVICE_PROVIDER"];

export type Permission =
  | "AUTH_READ_SELF"
  | "AUTH_UPDATE_SELF"
  | "FARM_MANAGE"
  | "PRODUCT_CREATE"
  | "PRODUCT_UPDATE"
  | "PRODUCT_DELETE"
  | "PRODUCT_READ_OWN"
  | "ORDER_READ_OWN"
  | "ORDER_MANAGE_OWN"
  | "NETWORK_CONNECT"
  | "NETWORK_MANAGE_OWN"
  | "SERVICE_MANAGE_OWN"
  | "SERVICE_QUOTE"
  | "AGENT_MANAGE_ASSIGNED_USERS"
  | "AGENT_MANAGE_LEADS"
  | "AGENT_MANAGE_TASKS"
  | "AGENT_REVIEW_VERIFICATION"
  | "ADMIN_VIEW_DASHBOARD"
  | "ADMIN_VIEW_USERS"
  | "ADMIN_EDIT_USERS"
  | "ADMIN_MANAGE_ROLES"
  | "ADMIN_SUSPEND_USERS"
  | "ADMIN_VIEW_PRODUCTS"
  | "ADMIN_MODERATE_PRODUCTS"
  | "ADMIN_VIEW_SERVICES"
  | "ADMIN_MODERATE_SERVICES"
  | "ADMIN_VIEW_VERIFICATIONS"
  | "ADMIN_REVIEW_VERIFICATIONS"
  | "ADMIN_VIEW_ORDERS"
  | "ADMIN_MANAGE_ORDER_ISSUES"
  | "ADMIN_VIEW_DISPUTES"
  | "ADMIN_MANAGE_DISPUTES"
  | "ADMIN_VIEW_REVIEWS"
  | "ADMIN_MODERATE_REVIEWS"
  | "ADMIN_VIEW_REPORTS"
  | "ADMIN_RESOLVE_REPORTS"
  | "ADMIN_VIEW_ANALYTICS"
  | "ADMIN_VIEW_NOTIFICATIONS"
  | "ADMIN_MANAGE_NOTIFICATIONS"
  | "ADMIN_VIEW_AUDIT_LOGS"
  | "ADMIN_MANAGE_SETTINGS"
  | "ADMIN_MANAGE_USERS"
  | "ADMIN_MANAGE_PRODUCTS"
  | "ADMIN_MANAGE_VERIFICATION"
  | "ADMIN_MANAGE_ORDERS";

export interface UserSession {
  userId: string;
  email: string;
  fullName: string;
  phone?: string | null;
  role: UserRole;
  status: UserStatus;
  tokenVersion: number;
}
